services:
  - type: web
    name: up-gov-chatbot-api
    env: python
    plan: free
    buildCommand: pip install uv && uv sync --frozen
    startCommand: uv run uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: CLUSTER_ENDPOINT
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false

  - type: static_site
    name: up-gov-chatbot-ui
    plan: free
    rootDir: i055.site/fmisc
    buildCommand: ""
    staticPublishPath: .
